MODEL:
  META_ARCHITECTURE: "Yolov3"
  DEVICE: "cuda"
  BACKBONE:
    NAME: "build_darknet_fpn_backbone"
  DAKRNET:
    NORM: "BN"
    STEM_OUT_CHANNELS: 32
    OUT_FEATURES: ["s3", "s4", "s5"]
    DEPTH: 53
    NUM_CLASSES: 0
  ANCHOR_GENERATOR:
    NAME: "YoloAnchorGenerator"
    SIZES: [[[10, 13], [16, 30], [33, 23]], [[30, 61], [62, 45], [59, 119]], [[116, 90], [156, 198], [373, 326]]]
  GRID_GENERATOR:
    NAME: "DefaultGridGenerator"
  STRIDE_GENERATOR:
    NAME: "DefaultStrideGenerator"
  DarknetFPN:
    IN_FEATURES: ["s3", "s4", "s5"]
    OUT_CHANNELS: [128, 256, 512]
  YOLOV3:
    NORM: "BN"
    NUM_CLASSES: 80
    IN_FEATURES: ["p3", "p4", "p5"]
    HEAD:
      OUT_CHANNELS: [256, 512, 1024]

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that Yolov3 uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000

INPUT:
  MIN_SIZE_TRAIN: (416,)
