_BASE_: "base_yolov3.yaml"
MODEL:
  WEIGHTS: "weights/darknet53.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 0
  
SOLVER:
  MAX_ITER: 300000
  CHECKPOINT_PERIOD: 50000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  BASE_LR: 0.001
  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupCosineLR