_BASE_: "base_darknet.yaml"

SOLVER:
  STEPS: (150000, 300000, 450000)
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 100000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  BASE_LR: 0.1
  IMS_PER_BATCH: 256