_BASE_: "base_mobilenetv2.yaml"

SOLVER:
  STEPS: (150000, 300000, 450000)
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 100000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  BASE_LR: 0.045
  IMS_PER_BATCH: 256
  LR_SCHEDULER_NAME: WarmupCosineLR