_BASE_: "base_shufflenetv1.yaml"

SOLVER:
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 100000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  BASE_LR: 0.1
  IMS_PER_BATCH: 256
  LR_SCHEDULER_NAME: WarmupCosineLR